#Indica que este consumidor va a leer solo una partición específica
#Necesario para que Spring Cloud Stream respete el orden
spring.cloud.stream.bindings.messageProcessor-in-0.consumer.partitioned=true
spring.cloud.stream.bindings.messageProcessor-in-0.consumer.instanceCount=2