spring.application.name=book-composite-service

server.port=7001
server.error.include-message=always

app.book-service.name=book-service

app.book-service.host=localhost
app.book-service.port=7002

app.recommendation-service.name=recommendation-service

app.recommendation-service.host=localhost
app.recommendation-service.port=7003

app.review-service.name=review-service

app.review-service.host=localhost
app.review-service.port=7004

logging.level.root=INFO
logging.level.com.amichetti=DEBUG

spring.cloud.stream.defaultBinder=rabbit
spring.cloud.stream.default.contentType=application/json

spring.cloud.stream.bindings.products-out-0.destination=products
spring.cloud.stream.bindings.products-out-0.producer.required-groups=auditGroup

spring.cloud.stream.bindings.recommendations-out-0.destination=recommendations
spring.cloud.stream.bindings.recommendations-out-0.producer.required-groups=auditGroup

spring.cloud.stream.bindings.reviews-out-0.destination=reviews
spring.cloud.stream.bindings.reviews-out-0.producer.required-groups=auditGroup

spring.cloud.stream.kafka.binder.brokers=127.0.0.1
spring.cloud.stream.kafka.binder.defaultBrokerPort=9092

spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoint.health.show-details=ALWAYS
management.endpoints.web.exposure.include=*












