
#partition-key-expression: headers['partitionKey']
# Toma la clave (key) de un header del mensaje llamado partitionKey
#Esta clave determina a qué partición va el mensaje
#Mensajes con la misma key implica misma partición implica orden garantizado

#partition-count: 2
#Define cuántas particiones tendrá el topic
#Más particiones implica más paralelismo
#Cada partición garantiza orden dentro de ella, pero el orden entre particiones no se garantiza

spring.cloud.stream.bindings.products-out-0.producer.partition-key-expression=headers['partitionKey']
spring.cloud.stream.bindings.products-out-0.producer.partition-count=2

spring.cloud.stream.bindings.recommendations-out-0.producer.partition-key-expression=headers['partitionKey']
spring.cloud.stream.bindings.recommendations-out-0.producer.partition-count=2

spring.cloud.stream.bindings.reviews-out-0.producer.partition-key-expression=headers['partitionKey']
spring.cloud.stream.bindings.reviews-out-0.producer.partition-count=2